function(ADM_EXTRA_WARNINGS)
  option(ADM_FATAL_WARNINGS "ADM_FATAL_WARNINGS" OFF)
  if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU" OR
      "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
      add_compile_options(-Wall)
      add_compile_options(-Wextra)
      if (ADM_FATAL_WARNINGS)
        add_compile_options(-Werror)
      else()
        message(STATUS "* * * A D M O B I L I Z E * * *")
        message(STATUS "Admobilize: Please treat warnings as errors. Use: -DADM_FATAL_WARNINGS=ON")
        message(STATUS "* * * * * * * * * * * * * * * *")
      endif()
  endif()
endfunction()
